// import useClient from 'react-server-components';
import Footer from './components/Footer';
import Header from './components/Header';
// import './globals.css';
import './global.scss';

export const metadata = {
  title: 'Dober',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  // useClient();

  return (
    <html lang="en">
      
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
      
    </html>
  )
}
