
import Link from "next/link";

import Advantages from "./components/Advantages";
import FirstSection from "./components/FirstSection";
import InfoForCompanies from "./components/InfoForCompanies";
import Possibilities from "./components/Possibilities";
import Security from "./components/Security";
import Subscribe from "./components/Subscribe";
import UseDober from "./components/UseDober";

// export const metadata = {
//   title: 'Main Dober',
//   description: 'Generated by create next app',
// } 

export default function Home() {
  return (
    <>
      <FirstSection />
      <Link href='/features'>
        <Possibilities />
      </Link>
      <Security />
      <Advantages />
      <UseDober />
      <Link href='/for_companies'> 
        <InfoForCompanies />
      </Link>
      <Subscribe />
    </>
  );
}
